### ISSUE TITLE
YouTube Video looks different

### ISSUE THREAD

**Issue by zhdenny** [omerxx/tmux-sessionx#74]
I just watched your youtube video about SessionX which brought me here....but I cannot seem to figure out how to make some configurations like you have in your video.

Screenshot of mine below. Notice the shortcut keys index are using Nerd Font glyphs. Also notice how the commands are written with "ctrl" instead of abbreviated as "C" for control-key.
![image](https://github.com/omerxx/tmux-sessionx/assets/26662131/baf6e37e-e3ad-41f3-bf24-a36878fa76ca)

Now here is screenshot from your [YouTube Video](https://www.youtube.com/watch?v=GH3kpsbbERo&t=414s) below.
How did you get your shortcut keys index to be words instead of Nerd Font Glyphs? How did you get your commands to use "C" to abbreviate "ctrl"?
![image](https://github.com/omerxx/tmux-sessionx/assets/26662131/1cded2a6-3398-4f7c-b388-c03fba16fab8)

**Comment by omerxx** [comment]
Hey!
The video's version is quite old and lots of contributions and changes were made since. 
The current version has these longer shortcuts shown.

What I think this issue can be converted to is 2 different new issues - 
1. Optional "abbreviated mode" where commands are shortened like the previous version
2. Another optional "no-nerd-font" config to use names rather than icons.

Hoping this satisfies the issue, feel free to reopen this one if it doesn't or the other two if you want them as a feature :)

**Comment by zhdenny** [comment]
You summarized it well. I would want to see these options added in a future update.

Should I open two new feature requests for you so this can be tracked?
